# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainuiform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.district = QtWidgets.QLabel(self.centralwidget)
        self.district.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.district.setStyleSheet("font: 14pt \"OCR A Extended\";")
        self.district.setObjectName("district")
        self.crop = QtWidgets.QLabel(self.centralwidget)
        self.crop.setGeometry(QtCore.QRect(120, 100, 61, 31))
        self.crop.setStyleSheet("font: 14pt \"OCR A Extended\";")
        self.crop.setObjectName("crop")
        self.language = QtWidgets.QLabel(self.centralwidget)
        self.language.setGeometry(QtCore.QRect(70, 130, 91, 31))
        self.language.setStyleSheet("font: 14pt \"OCR A Extended\";")
        self.language.setObjectName("language")
        self.district_input = QtWidgets.QLineEdit(self.centralwidget)
        self.district_input.setGeometry(QtCore.QRect(190, 80, 161, 23))
        self.district_input.setText("")
        self.district_input.setObjectName("district_input")
        self.crop_input = QtWidgets.QLineEdit(self.centralwidget)
        self.crop_input.setGeometry(QtCore.QRect(191, 110, 161, 23))
        self.crop_input.setText("")
        self.crop_input.setObjectName("crop_input")
        self.language_input = QtWidgets.QLineEdit(self.centralwidget)
        self.language_input.setGeometry(QtCore.QRect(190, 140, 161, 23))
        self.language_input.setText("")
        self.language_input.setObjectName("language_input")
        self.infromation_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.infromation_output.setGeometry(QtCore.QRect(370, 70, 351, 491))
        self.infromation_output.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.infromation_output.setObjectName("infromation_output")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(112, 190, 191, 28))
        self.submit_button.setStyleSheet("font: 14pt \"OCR A Extended\";")
        self.submit_button.setObjectName("submit_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 10, 161, 31))
        self.label.setStyleSheet("font: 14pt \"OCR A Extended\";")
        self.label.setObjectName("label")
        self.play_sound_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_sound_button.setGeometry(QtCore.QRect(720, 70, 75, 23))
        self.play_sound_button.setObjectName("play_sound_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.district.setText(_translate("MainWindow", "District"))
        self.crop.setText(_translate("MainWindow", "Crop"))
        self.language.setText(_translate("MainWindow", "Language"))
        self.submit_button.setText(_translate("MainWindow", "get information"))
        self.label.setText(_translate("MainWindow", "PandaFarm"))
        self.play_sound_button.setText(_translate("MainWindow", "play sound"))
